### ISSUE TITLE
Make a howto/tutorial from scratch

### ISSUE THREAD

**Issue by wesley974** [Mariosts95/delsuites#38]
Hello, i tried what you did, this is awesome, can you contact me please?
Thanks

**Comment by Mariosts95** [comment]
Hello, how can I help you?

**Comment by wesley974** [comment]
Im learning js/react, possible for you to make a full tutorial from scratch?

**Comment by Mariosts95** [comment]
I can help you if there is something specific, otherwise I don't have time to make a tutorial at the moment.
There are plenty of tutorials and videos on the web. Here are some sources that helped me:

- https://www.youtube.com/c/WebDevSimplified
- https://www.youtube.com/c/Fireship
- https://www.udemy.com/course/the-complete-javascript-course/
- https://www.udemy.com/course/react-the-complete-guide-incl-redux/

**Comment by wesley974** [comment]
Thank's!
